// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/fetcher/fetcher.go

package mock

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Fetcher interface
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockFetcherRecorder
}

// Recorder for MockFetcher (not exported)
type _MockFetcherRecorder struct {
	mock *MockFetcher
}

func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &_MockFetcherRecorder{mock}
	return mock
}

func (_m *MockFetcher) EXPECT() *_MockFetcherRecorder {
	return _m.recorder
}

func (_m *MockFetcher) Fetch(url string) (*bytes.Buffer, error) {
	ret := _m.ctrl.Call(_m, "Fetch", url)
	ret0, _ := ret[0].(*bytes.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFetcherRecorder) Fetch(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fetch", arg0)
}
