// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/parser/parser.go

package mock

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Parser interface
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *_MockParserRecorder
}

// Recorder for MockParser (not exported)
type _MockParserRecorder struct {
	mock *MockParser
}

func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &_MockParserRecorder{mock}
	return mock
}

func (_m *MockParser) EXPECT() *_MockParserRecorder {
	return _m.recorder
}

func (_m *MockParser) Parse(body *bytes.Buffer, ch chan interface{}, stop chan bool) {
	_m.ctrl.Call(_m, "Parse", body, ch, stop)
}

func (_mr *_MockParserRecorder) Parse(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parse", arg0, arg1, arg2)
}
