// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/validator/validator.go

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of ValidatorInterface interface
type MockValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockValidatorInterfaceRecorder
}

// Recorder for MockValidatorInterface (not exported)
type _MockValidatorInterfaceRecorder struct {
	mock *MockValidatorInterface
}

func NewMockValidatorInterface(ctrl *gomock.Controller) *MockValidatorInterface {
	mock := &MockValidatorInterface{ctrl: ctrl}
	mock.recorder = &_MockValidatorInterfaceRecorder{mock}
	return mock
}

func (_m *MockValidatorInterface) EXPECT() *_MockValidatorInterfaceRecorder {
	return _m.recorder
}

func (_m *MockValidatorInterface) Validate(url string) (bool, string) {
	ret := _m.ctrl.Call(_m, "Validate", url)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

func (_mr *_MockValidatorInterfaceRecorder) Validate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate", arg0)
}
